# Generated by Django 5.1.5 on 2025-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('created_at', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=10, max_digits=19)),
                ('size', models.CharField(max_length=300)),
                ('mouth_size', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('suppliedby', models.CharField(max_length=300)),
                ('current_quantity', models.BigIntegerField()),
            ],
        ),
    ]
