# Generated by Django 5.1.5 on 2025-02-20 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbottle',
            name='suppliedby',
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
